name: welcome_comp
description: "Welcome Comp is an app created to bring together content from the Computer Science course subjects at the Federal University of Maranhão"
publish_to: 'none' 
version: 1.0.1+4

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^11.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/logo_welcome_comp.png
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900